# Custom Language File for Launcher Customizer

[ejs.app]
title = "The last of craft"

[ejs.landing]
mediaGitHubURL = ""
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/ZDpMbC7GMD"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO THE LAST OF CRAFT"
welcomeDescription = "Discover an apocalyptic post of radioactive creatures as well as zombies. In this world, you will be able to create your alliance with equipped players quickly because of the rodent creatures in the streets!"
welcomeDescCTA = "You are just a few clicks."
